stages:
  - build
  - dev_build
  - notify_failure

production_build:
  stage: build
  only:
    - master
  tags:
    - ROTOPROS
  script:
    - npm install
    - ng build --prod -extract-css false
    - cd /home/ubuntu/builds/ffbe2209/0/anonymous-coder/RotoProsWeb
    - rm -rf /var/www/html/RotoProsWeb/dist
    - cp -R /home/ubuntu/builds/ffbe2209/0/anonymous-coder/RotoProsWeb/dist /var/www/html/RotoProsWeb/
  tags:
    - ROTOPROS

production_dev_build:
  stage: dev_build
  only:
    - staging
  script:
    - npm install
    - ng build --prod --env=dev -extract-css false
    - cd /home/gitlab-runner/builds/03bf9824/0/anonymous-coder/RotoProsWeb
    - rm -rf /var/www/html/RotoProsWeb/dist
    - cp -R /home/gitlab-runner/builds/03bf9824/0/anonymous-coder/RotoProsWeb/dist /var/www/html/RotoProsWeb/
  tags:
    - RP
